import Head from 'next/head'
import Layout from './Components/Layout'
import Hero from './Components/Hero'
import Carousel from './Components/Carousel'
import Video from './Components/Video'

import ProjectFiles from './Components/ProjectFiles'
import FeaturedOne from './Components/FeaturedOne'



import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
     <Head>
        <title>La Belle Vita</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>
      <Layout>
        <Hero />
        <Video />
        <FeaturedOne />
         
        <ProjectFiles /> 
      </Layout>

    </>
  )
}
